version: "3.9"
services:
    
    db:
        image: "mcr.microsoft.com/mssql/server"
        container_name: db
        environment:
            SA_PASSWORD: "vV5r9tn0M4@"
            ACCEPT_EULA: "Y"
        ports:
          - "1433:1433"
        networks: 
            - multiappnet



networks:
    multiappnet:
        driver: bridge
 
